#!/bin/bash

IMAGES=(
####################

######## app #######
app/hello-world:latest
app/server-test:production

####################
)

if [ "$DEBUG" == "1" ] ; then
  echo "Image list test"
  for img in ${IMAGES[@]}; do
    echo "Image : $img"
  done
  echo "-------------"
  echo "Done."

#  while true; do
#    read -p "Do you run to deploy using these images (y/n)? " yn
#    case $yn in
#        [Yy]* ) break ;;
#        [Nn]* ) exit ;;
#        * ) echo "Please answer yes or no. ";;
#    esac
#  done
fi
